<a href="https://colab.research.google.com/github/pridenous/NumPyLeasson/blob/master/eighthLeasson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Algebra and Size**

In [ ]:
import numpy as np
import sys

Membuat variabel array, **a = 3 Dimensi** dan **b = 2 Dimensi**

In [ ]:
# a = np.random.randint(100,size=(3,3))
a = np.array([[49, 62, 27],
       [88,  6, 11],
       [74, 35, 51]])
a

array([[49, 62, 27],
       [88,  6, 11],
       [74, 35, 51]])

In [ ]:
# b = np.random.randint(50,size=(3,2))
b = np.array([[ 2,  9],
       [ 9, 28],
       [34, 44]])
b

array([[ 2,  9],
       [ 9, 28],
       [34, 44]])

**Operasi Matriks** <h5>
*Maka didapat,* <h5>,


>$a =
 \begin{pmatrix}
  {49} & {62} & {27} \\
  {88} & {6} & {11} \\
  {74} & {35} & {51} 
 \end{pmatrix}$

 dan ,
 >$b =
 \begin{pmatrix}
  {2} &  {9} \\
  {9} & {28} \\
  {34} &  {44} 
 \end{pmatrix}$
 






**Perkalian beda matriks** <h5>
operasi pada matriks ($a.b$)

In [ ]:
a.dot(b)

array([[1574, 3365],
       [ 604, 1444],
       [2197, 3890]])

In [ ]:
a @ b 

array([[1574, 3365],
       [ 604, 1444],
       [2197, 3890]])

**Transpos Matriks**

operasi matriks dengan mentransposkan array $b$ = $b^T$

In [ ]:
b #array sebelum transpos

array([[ 2,  9],
       [ 9, 28],
       [34, 44]])

In [ ]:
b.T # array sesudah transpos

array([[ 2,  9, 34],
       [ 9, 28, 44]])

Operasi matriks $b^T$$. a$

In [ ]:
b.T @ a

array([[3406, 1368, 1887],
       [6161, 2266, 2795]])

# **Size of Object in Memory**

dapat dikatakan, angka **3** di python memakan resource sebesar `28 Bytes` tanpa **NumPy**

In [ ]:
sys.getsizeof(3)

28

didapatkan juga tipe data **long** memakan lebih banyak resource dibanding integer tanpa **NumPy**

In [ ]:
sys.getsizeof(10**100)

72

In [ ]:
sys.getsizeof(int)

400

In [ ]:
np.dtype(int).itemsize #resouce integer per satu angka dengan NumPy

8

In [ ]:
np.dtype(float).itemsize #resource float per satu angka dengan NumPy

8

In [ ]:
np.dtype(np.int8).itemsize

1

**Size of List**

In [ ]:
sys.getsizeof([1]) #List Without NumPy

72

In [ ]:
np.array([1]).nbytes #Array use NumPy

8

**Perfomance is Important**

In [ ]:
l = list(range(1000))
l #Variabel List With Python

In [ ]:
a = np.arange(1000)
a #Variabel Array with NumPy

Kecepatan dalam mengeksekusi/memproses data sangat penting dalam pemrograman

``Array a`` <h5>
Dapat dilihat Array menggunakan numpy terlihat lebih cepat diproses

In [ ]:
%time np.sum(a ** 2)

CPU times: user 177 µs, sys: 21 µs, total: 198 µs
Wall time: 186 µs


332833500

``List l`` <h5>
sedangkan list dengan Phyton sedikit lebih tertinggal dibanding array dengan NumPy

In [ ]:
%time sum([x**2 for x in l])

CPU times: user 328 µs, sys: 0 ns, total: 328 µs
Wall time: 332 µs


332833500