<a href="https://colab.research.google.com/github/pridenous/NumPyLeasson/blob/master/eighthLeasson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Algebra and Size**

In [2]:
import numpy as np

Membuat variabel array, **a = 3 Dimensi** dan **b = 2 Dimensi**

In [28]:
a = np.random.randint(100,size=(3,3))
a

array([[49, 62, 27],
       [88,  6, 11],
       [74, 35, 51]])

In [29]:
b = np.random.randint(50,size=(3,2))
b

array([[ 2,  9],
       [ 9, 28],
       [34, 44]])

**Operasi Matriks** <h5>
*Maka didapat,* <h5>,


>$a =
 \begin{pmatrix}
  {49} & {62} & {27} \\
  {88} & {6} & {11} \\
  {74} & {35} & {51} 
 \end{pmatrix}$

 dan ,
 >$b =
 \begin{pmatrix}
  {2} &  {9} \\
  {9} & {28} \\
  {34} &  {44} 
 \end{pmatrix}$
 






**Perkalian beda matriks** <h5>
operasi pada matriks ($a.b$)

In [31]:
a.dot(b)

array([[1574, 3365],
       [ 604, 1444],
       [2197, 3890]])

In [32]:
a @ b 

array([[1574, 3365],
       [ 604, 1444],
       [2197, 3890]])

**Transpos Matriks**

operasi matriks dengan mentransposkan array $b$ = $b^T$

In [34]:
b #array sebelum transpos

array([[ 2,  9],
       [ 9, 28],
       [34, 44]])

In [35]:
b.T # array sesudah transpos

array([[ 2,  9, 34],
       [ 9, 28, 44]])