<a href="https://colab.research.google.com/github/pridenous/NumPyLeasson/blob/master/fifthLeasson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sys
import numpy as np

In [2]:
np.array([1,2,4,5])

array([1, 2, 4, 5])

In [3]:
np.int8

numpy.int8

In [6]:
a = np.array([1,2,3,4])

In [8]:
a.dtype

dtype('int64')

In [12]:
b = np.array([2,3,5,4], dtype=np.int8)

In [14]:
b.dtype

dtype('int8')

# **Multidimensional Array**

In [15]:
c = np.array([
              [1,2,3],
              [5,6,7]
])

In [16]:
c.shape

(2, 3)

In [18]:
c.ndim

2

In [19]:
c.size

6

In [21]:
d = np.array([
              [
               [1,2,3],
               [2,3,6]
              ],
              [
               [1,2,4],
               [6,3,1]
              ]

])

In [22]:
d

array([[[1, 2, 3],
        [2, 3, 6]],

       [[1, 2, 4],
        [6, 3, 1]]])

In [23]:
d.shape

(2, 2, 3)

In [26]:
d.ndim

3

In [27]:
d.size

12

# **Matrix**

In [33]:
e = np.array([
    #.         0 1 2         
              [1,2,3],   #. 1
              [5,6,7],   #. 2
              [8,9,11]   #. 3
])

In [30]:
e[1]  #. Selecting Rows 1

array([5, 6, 7])

In [32]:
e[1][2] #. Selecting Rows 1, Columns 2 

7

In [34]:
e[0:2]

array([[1, 2, 3],
       [5, 6, 7]])

Make Skip symbol (:) for array skip

In [36]:
e[:,2] #. Skip row 0-1, and show columns 2

array([ 3,  7, 11])

In [37]:
e[2,:] #. Show Row 2, and skip row 0-2

array([ 8,  9, 11])

In [41]:
e[:2,2:]

array([[3],
       [7]])

Assign new array to base array

In [42]:
e[1] = [18,1,2]

In [43]:
e

array([[ 1,  2,  3],
       [18,  1,  2],
       [ 8,  9, 11]])

In [44]:
e[2] = 10

In [45]:
e

array([[ 1,  2,  3],
       [18,  1,  2],
       [10, 10, 10]])

# Summary Statistic

In [46]:
f = np.array([1,2,3,4])

In [47]:
f.sum()

10

In [48]:
f.mean()

2.5

In [49]:
f.std()

1.118033988749895

In [50]:
f.var()

1.25

In [51]:
f = np.array([
              [1,2,3],
              [5,6,7],
              [8,9,10]
])

In [52]:
f.sum()

51

In [53]:
f.mean()

5.666666666666667

In [54]:
f.std()

2.9814239699997196

In [55]:
f.var()

8.88888888888889

In [56]:
f.sum(axis=0)  #. vertical

array([14, 17, 20])

In [59]:
f.sum(axis=1) #. horizontal

array([ 6, 18, 27])

In [60]:
f.mean(axis=0)

array([4.66666667, 5.66666667, 6.66666667])

In [61]:
f.mean(axis=1)

array([2., 6., 9.])