<a href="https://colab.research.google.com/github/pridenous/NumPyLeasson/blob/master/seventhLeasson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Boolean Operation**
Seleksi numpy pada array boolean

In [1]:
import numpy as np

In [2]:
a = np. arange(4)
a

array([0, 1, 2, 3])

Contoh seleksi dengan cara **normal**

In [6]:
a[[0,-1]] #seleksi baris 0, dan kolom -1 (yg berarti -1 dari total kolom yang ada 

array([0, 3])

Contoh seleksi dengan **boolean**

In [8]:
a[[True,False,False,True]]

array([0, 3])

Dapat dikatakan cara diatas masih belum efektif jika array yang ditampung berjumlah **ribuan** atau **miliaran**. maka dapat diefektifkan dengan menambahkan kondisi array yang akan diseleksi.

In [9]:
a >= 2

array([False, False,  True,  True])

In [12]:
a[a >= 2] #seleksi nilai array diatas angka 2)

array([2, 3])

# **Spesifik Penyeleksian Array**

In [13]:
a.mean() #Mendapatkan nilai rata-rata dari nilai array a

1.5

In [17]:
a[a > a.mean()] #Seleksi nilai array diatas nilai rata yakni 1,5

array([2, 3])

In [22]:
a[~(a > a.mean())] #Seleksi nilai array tidak termasuk(bukan) diatas rata-rata, simbol not ditandai dengan ~

array([0, 1])

In [25]:
a[(a == 0) | (a == 1)] #Seleski nilai array dengan operasi OR

array([0, 1])

In [27]:
a[(a <=2) & (a % 2 == 0)] #Seleksi nilai array menggunakan operasi AND, (tambahan, untuk proses seleksi menggunakan modulasi)

array([0, 2])

**Seleksi Array Multidimensi**


In [33]:
b = np.random.randint(100, size=(3,3)) #Membuat array dengan dimensi 3x3 serta diisi angka random dari 0-100
b

array([[40, 51, 14],
       [ 2, 79, 72],
       [89, 13, 75]])

Berikut adalah contoh seleksi array dengan boolean normal namun masih dikategorikan kurang efektif

In [35]:
b[np.array([
              [False, True, False],
              [False, True, True],
              [True, False, True]
])]

array([51, 79, 72, 89, 75])

*Penyederhanaan :*

In [37]:
b>=51

array([[False,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

In [38]:
b[b>=51] # Seleksi Array dengan kondisi

array([51, 79, 72, 89, 75])