<a href="https://colab.research.google.com/github/pridenous/NumPyLeasson/blob/master/sixthLeasson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [14]:
a = np.arange(4)

In [15]:
a

array([0, 1, 2, 3])

Tambah tiap elemen array **a** dengan angka **10**

In [16]:
a + 10

array([10, 11, 12, 13])

Kasus perkalian

In [9]:
a * 10

array([ 0, 10, 20, 30])

dalam kasus diatas variabel **a** tidak mengalami perubahan, dikarenakan perintah diatas mengoprasikan jenis array baru bukan mengganti atau merubah nilai pada variabel **a**

In [10]:
a

array([0, 1, 2, 3])

melakukan operasi perhitungan serta merubah nilai **a**

In [17]:
a += 100

In [18]:
a

array([100, 101, 102, 103])

In [19]:
a *= 100

In [20]:
a

array([10000, 10100, 10200, 10300])

Operasi **list**

In [21]:
l = [1,2,3,4]

In [23]:
[i*10 for i in l]

[10, 20, 30, 40]

Operasi hitung pada 2 array

In [26]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [28]:
b = np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [29]:
a + b

array([10, 21, 32, 43])